Refactor: Separate build and deploy steps in firebase-hosting-merge.yml and firebase-hosting-pull-request.yml

diff --git a/.github/workflows/firebase-hosting-merge.yml b/.github/workflows/firebase-hosting-merge.yml
--- a/.github/workflows/firebase-hosting-merge.yml
+++ b/.github/workflows/firebase-hosting-merge.yml
@@ -7,7 +7,7 @@ on:
     branches:
       - main
 jobs:
-  build_and_deploy:
+  build:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v4
@@ -19,6 +19,52 @@ jobs:
 
       - name: Build (yarn)
         run: yarn run build
+
+      - name: Get current directory
+        run: |
+          pwd
+          ls -la
+
+      - name: Verify dist directory
+        run: |
+          if [ ! -d "dist" ]; then
+            echo "Error: dist directory does not exist."
+            exit 1
+          fi
+
+      - name: Upload dist folder
+        uses: actions/upload-artifact@v4
+        with:
+          name: dist
+          path: dist/
+  
+
+  
+  deploy_live:
+    needs: build
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v4
+
+      - name: Re-create dist folder
+        run: |
+          mkdir dist
+      - name: Download dist folder
+        uses: actions/download-artifact@v4
+        with:
+          name: dist
+        
+      - name: Get current directory
+        run: |
+          pwd
+          ls -la
+
+      - name: Verify dist directory
+        run: |
+          if [ ! -d "dist" ]; then
+            echo "Error: dist directory does not exist."
+            exit 1
+          fi
 
       - uses: FirebaseExtended/action-hosting-deploy@v0
         with:
diff --git a/.github/workflows/firebase-hosting-pull-request.yml b/.github/workflows/firebase-hosting-pull-request.yml
--- a/.github/workflows/firebase-hosting-pull-request.yml
+++ b/.github/workflows/firebase-hosting-pull-request.yml
@@ -9,24 +9,68 @@ on:
   push:
     branches:
       - preview/*
-  
+
 permissions:
   checks: write
   contents: read
   pull-requests: write
 jobs:
-  build_and_preview:
+  build:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v4
       - name: Enable Corepack before setting up Node
         run: corepack enable
-      
+
       - name: Install Dependencies
         run: yarn install
 
       - name: Build (yarn)
         run: yarn run build
+
+      - name: Get current directory
+        run: |
+          pwd
+          ls -la
+
+      - name: Verify dist directory
+        run: |
+          if [ ! -d "dist" ]; then
+            echo "Error: dist directory does not exist."
+            exit 1
+          fi
+      - name: Upload dist folder
+        uses: actions/upload-artifact@v4
+        with:
+          name: dist
+          path: dist/
+
+  deploy_preview:
+    needs: build
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v4
+
+      - name: Re-create dist folder
+        run: |
+          mkdir dist
+      - name: Download dist folder
+        uses: actions/download-artifact@v4
+        with:
+          name: dist
+        
+      - name: Get current directory
+        run: |
+          pwd
+          ls -la
+
+      - name: Verify dist directory
+        run: |
+          if [ ! -d "dist" ]; then
+            echo "Error: dist directory does not exist."
+            exit 1
+          fi
 
       - uses: FirebaseExtended/action-hosting-deploy@v0
         with:
